### ISSUE TITLE
Staff application for moderator. 

### ISSUE THREAD

**Issue by handsomesexybitch** [HeistersDiscord/HelpTickets#1]
I would like to apply for moderator. I have been a moderator for 3 servers since months ago, and i have gain lost of experience during that time. But due to personal problems i had to quit for a while. And now everything is fine, i would like to resume to be a moderator. During my times of moderation, i have been exposed to the different moderation bots and have learnt quite a few things about the bots and have known how to use them. I have also done a good job for a server by finding out the culprit who abused power and ruin the server. As a moderator i would be on a lookout in channels for people causing havoc or misbehaving, and give them the appropriate punishment. I would also inform higher rank people if i see any person higher rank than me abusing power or breaking rules. I am active quite often in discord thus i can dedicate the time to be a moderator in the server, even though i am a mod in another server currently but that server is kinda dead, thus i am looking around to be a moderator. Lastly my timezone MYT, which might help as some of the staff has different timezone, thus at different times there would be a staff active on the server to help moderate the server by helping people and taking care of the server. Thank you

**Comment by kk5dire** [comment]
@handsomesexybitch  congrats on being aproved 😄
